# Use MySQL database
db=mysql

# JDBC URL (adapté à ton host, port et base)
db-url=jdbc:mysql://localhost:3308/keycloakdb?useSSL=false&allowPublicKeyRetrieval=true

# Credentials
db-username=hugues
db-password=2004

# Show SQL logs if needed (utile en debug)
# log-level=DEBUG
# log-level-org.hibernate.SQL=DEBUG