spring.application.name=finpulse-explainer
server.port=8082

# Mistral API
mistral.api.key=jrR7NFwhKhXQQYiNEsYcBryTB0PaD5A7
mistral.api.url=https://api.mistral.ai/v1/chat/completions
mistral.model=mistral-large-latest

# Fallback template si Mistral échoue
explainer.fallback.enabled=true
logging.level.com.finpulse.explainer=DEBUG