spring.application.name=backend
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/Finpulse-db
spring.datasource.username=postgres
spring.datasource.password=3125
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/finpulse
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/finpulse/protocol/openid-connect/certs

keycloak.server-url=http://localhost:8080
keycloak.realm=finpulse
keycloak.client-id=finpulse-backend
keycloak.client-secret=T2TEEYKOELMwqClSeEIZfAFKxyYLuvEv
keycloak.admin-realm=master

cors.allowed-origins=http://localhost:4200
logging.level.com.finpulse=DEBUG
logging.level.org.springframework.security=INFO

spring.ai.openai.api-key=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

finpulse.upload.avatars-dir=uploads/avatars
finpulse.upload.base-url=http://localhost:8081

spring.web.resources.static-locations=classpath:/static/,file:uploads/

finpulse.alphavantage.api-key=NE8NU2F24VQJWF3U

# Multipart upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

# WebClient (pour Alpha Vantage)
spring.codec.max-in-memory-size=2MB

logging.level.ma.enset=DEBUG
