# SERVER & BASIC CONFIG
server.port=8081
spring.application.name=FinPulse-Backend-Integrated

# KEYCLOAK AUTHENTIFICATION
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/finpulse
keycloak.server-url=http://keycloak:9090
keycloak.realm=finpulse
keycloak.client-id=finpulse-backend
keycloak.client-secret=xxxxx
keycloak.admin.username=admin
keycloak.admin.password=admin

# DATABASE PRINCIPALE
spring.datasource.url=jdbc:postgresql://postgres:5432/Finpulse-db
spring.datasource.username=postgres
spring.datasource.password=3125
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=10
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.hbm2ddl.halt_on_error=false

# REDIS CACHE
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.database=0
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000

# AI ENGINES
spring.ai.mistralai.api-key=xxxxxx
spring.ai.mistralai.chat.options.model=mistral-large-latest
spring.ai.mistralai.chat.options.temperature=0.7

# EXTERNAL APIS
finpulse.alphavantage.api-key=xxxxxx
p1.api.url=http://localhost:8000
finpulse.simulation.enabled=false
finpulse.p1.poll-interval=120000

# FILE UPLOAD
finpulse.upload.avatars-dir=uploads/avatars
finpulse.upload.base-url=http://localhost:8081
finpulse.upload.max-size=5242880

# LOGGING
logging.level.root=INFO
logging.level.ma.enset.backend=DEBUG